#include "creatures/creatures.h"

const animal_specs_t animals[] = {
    // Name	Str	Dex	Con	AC Reach Grapp Fort Ref Will S1 S2
    {"Ape",
     SIZE_LARGE,
     4,
     TYPE_ANIMAL,
     21,
     15,
     14,
     14,
     10,
     15,
     13,
     9,
     16,
     {{MG_LAND, 30}, {MG_CLIMB, 30}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 1, 6, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Bear Brown",
     SIZE_LARGE,
     6,
     TYPE_ANIMAL,
     27,
     13,
     19,
     15,
     5,
     18,
     15,
     8,
     16,
     {{MG_LAND, 30}, {MG_NONE, 0}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 1, 8, 0}, {NW_BITE, NAR_SECONDARY, 0, 2, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_IMPROVED_GRAB, 1}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Bear Polar",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     27,
     13,
     19,
     15,
     5,
     18,
     15,
     8,
     16,
     {{MG_LAND, 40}, {MG_SWIM, 30}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Bison",
     SIZE_LARGE,
     5,
     TYPE_ANIMAL,
     22,
     10,
     16,
     13,
     5,
     16,
     14,
     7,
     16,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_GORE, NAR_PRIMARY, 0, 1, 8, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Camel",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     18,
     16,
     14,
     13,
     5,
     14,
     13,
     10,
     16,
     {{MG_LAND, 50}, {MG_NONE, 0}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Dire Ape",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     22,
     15,
     14,
     15,
     10,
     16,
     13,
     9,
     16,
     {{MG_LAND, 30}, {MG_CLIMB, 15}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Dire Bat",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     17,
     22,
     17,
     20,
     5,
     13,
     14,
     13,
     16,
     {{MG_LAND, 20}, {MG_FLY_GOOD, 40}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Dire Bear",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     31,
     13,
     19,
     17,
     5,
     20,
     15,
     8,
     16,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Dire Boar",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     27,
     10,
     17,
     15,
     5,
     18,
     14,
     7,
     16,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Dire Lion",
     SIZE_LARGE,
     8,
     TYPE_ANIMAL,
     25,
     15,
     17,
     15,
     5,
     17,
     14,
     9,
     16,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 1, 6, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 8, 0}, {NW_RAKE, NAR_SPECIAL, 0, 1, 6, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_IMPROVED_GRAB, 1}, {SA_POUNCE, 1}, {SA_RAKE, 2}}}},
    {"Dire Tiger",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     27,
     15,
     17,
     17,
     5,
     18,
     14,
     9,
     16,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Dire Wolf",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     25,
     15,
     17,
     14,
     5,
     17,
     14,
     9,
     16,
     {{MG_LAND, 50}, {MG_NONE, 0}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Dire Wolverine",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     22,
     17,
     19,
     16,
     5,
     16,
     15,
     10,
     16,
     {{MG_LAND, 30}, {MG_BURROW, 10}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Horse Heavy",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     16,
     13,
     15,
     13,
     5,
     13,
     13,
     8,
     16,
     {{MG_LAND, 50}, {MG_NONE, 0}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Horse Light",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     14,
     13,
     15,
     13,
     5,
     12,
     13,
     8,
     16,
     {{MG_LAND, 60}, {MG_NONE, 0}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Lion",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     21,
     17,
     15,
     15,
     5,
     15,
     13,
     10,
     16,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Manta Ray",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     15,
     11,
     10,
     12,
     5,
     12,
     11,
     7,
     16,
     {{MG_SWIM, 30}, {MG_NONE, 0}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Mule",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     16,
     13,
     17,
     13,
     5,
     13,
     14,
     8,
     16,
     {{MG_LAND, 30}, {MG_NONE, 0}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Octopus, Giant",
     SIZE_LARGE,
     8,
     TYPE_ANIMAL,
     20,
     15,
     13,
     18,
     10,
     15,
     12,
     9,
     16,
     {{MG_LAND, 20}, {MG_SWIM, 40}},
     {{{NW_TENTACLE, NAR_PRIMARY, 0, 1, 4, 0},
       {NW_BITE, NAR_SECONDARY, 0, 1, 8, 0},
       {NW_CONSTRICT, NAR_SPECIAL, ATTACK_PRESET, 2, 8, 6}},
      {{NW_TENTACLE, 8}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_IMPROVED_GRAB, 1}, {SA_CONSTRICT, 1}, {SA_NONE, 0}}}},
    {"Rhinoceros",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     26,
     10,
     21,
     16,
     5,
     18,
     16,
     7,
     16,
     {{MG_LAND, 30}, {MG_NONE, 0}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Shark, Large",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     17,
     15,
     13,
     15,
     5,
     13,
     12,
     9,
     16,
     {{MG_SWIM, 60}, {MG_NONE, 0}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Viper, Large",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     10,
     17,
     11,
     15,
     5,
     10,
     11,
     10,
     16,
     {{MG_LAND, 20}, {MG_SWIM, 20}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Tiger",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     23,
     15,
     17,
     14,
     5,
     16,
     14,
     9,
     16,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Warhorse Heavy",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     18,
     13,
     17,
     14,
     5,
     14,
     14,
     8,
     16,
     {{MG_LAND, 50}, {MG_NONE, 0}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
    {"Warhorse Light",
     SIZE_LARGE,
     -1,
     TYPE_ANIMAL,
     16,
     13,
     17,
     14,
     5,
     13,
     14,
     8,
     16,
     {{MG_LAND, 60}, {MG_NONE, 0}},
     {{{NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}}},
};

const size_t total_creatures = sizeof(animals) / sizeof(animal_specs_t);
