#include "creatures/creatures.h"

#include "specs/attacks.h"

const animal_specs_t animals[] = {
    // Name	Str	Dex	Con	AC Reach Grapp Fort Ref Will S1 S2
    {"Ape",
     SIZE_LARGE,
     4,
     TYPE_ANIMAL,
     21,
     15,
     14,
     14,
     10,
     15,
     13,
     9,
     16,
     {{MG_LAND, 30}, {MG_CLIMB, 30}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 1, 6, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Bear Brown",
     SIZE_LARGE,
     6,
     TYPE_ANIMAL,
     27,
     13,
     19,
     15,
     5,
     18,
     15,
     8,
     16,
     {{MG_LAND, 30}, {MG_NONE, 0}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 1, 8, 0}, {NW_BITE, NAR_SECONDARY, 0, 2, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_IMPROVED_GRAB, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Bear Polar",
     SIZE_LARGE,
     8,
     TYPE_ANIMAL,
     27,
     13,
     19,
     15,
     5,
     18,
     15,
     8,
     16,
     {{MG_LAND, 40}, {MG_SWIM, 30}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 1, 8, 0}, {NW_BITE, NAR_SECONDARY, 0, 2, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_IMPROVED_GRAB, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Bison",
     SIZE_LARGE,
     5,
     TYPE_ANIMAL,
     22,
     10,
     16,
     13,
     5,
     16,
     14,
     7,
     16,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_GORE, NAR_PRIMARY, 0, 1, 8, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Camel",
     SIZE_LARGE,
     3,
     TYPE_ANIMAL,
     18,
     16,
     14,
     13,
     5,
     14,
     13,
     10,
     16,
     {{MG_LAND, 50}, {MG_NONE, 0}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 4, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Dire Ape",
     SIZE_LARGE,
     5,
     TYPE_ANIMAL,
     22,
     15,
     14,
     15,
     10,
     16,
     13,
     9,
     16,
     {{MG_LAND, 30}, {MG_CLIMB, 15}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 1, 6, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 8, 0}, {NW_REND, NAR_SPECIAL, 0, 2, 6, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_REND, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Dire Bat",
     SIZE_LARGE,
     4,
     TYPE_ANIMAL,
     17,
     22,
     17,
     20,
     5,
     13,
     14,
     13,
     16,
     {{MG_LAND, 20}, {MG_FLY_GOOD, 40}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 8, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Dire Bear",
     SIZE_LARGE,
     12,
     TYPE_ANIMAL,
     31,
     13,
     19,
     17,
     5,
     20,
     15,
     8,
     16,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 2, 4, 0}, {NW_BITE, NAR_SECONDARY, 0, 2, 8, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_IMPROVED_GRAB, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Dire Boar",
     SIZE_LARGE,
     7,
     TYPE_ANIMAL,
     27,
     10,
     17,
     15,
     5,
     18,
     14,
     7,
     16,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_GORE, NAR_PRIMARY, 0, 1, 8, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_GORE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_FEROCITY, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Dire Lion",
     SIZE_LARGE,
     8,
     TYPE_ANIMAL,
     25,
     15,
     17,
     15,
     5,
     17,
     14,
     9,
     16,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 1, 6, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 8, 0}, {NW_RAKE, NAR_SPECIAL, 0, 1, 6, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_IMPROVED_GRAB, 1}, {SA_POUNCE, 1}, {SA_RAKE, 2}}},
     ""},
    {"Dire Tiger",
     SIZE_LARGE,
     16,
     TYPE_ANIMAL,
     27,
     15,
     17,
     17,
     5,
     18,
     14,
     9,
     16,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 2, 4, 0}, {NW_BITE, NAR_SECONDARY, 0, 2, 6, 0}, {NW_RAKE, NAR_SPECIAL, 0, 2, 4, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_IMPROVED_GRAB, 1}, {SA_POUNCE, 1}, {SA_RAKE, 2}}},
     ""},
    {"Dire Wolf",
     SIZE_LARGE,
     6,
     TYPE_ANIMAL,
     25,
     15,
     17,
     14,
     5,
     17,
     14,
     9,
     16,
     {{MG_LAND, 50}, {MG_NONE, 0}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 8, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_TRIP, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Dire Wolverine",
     SIZE_LARGE,
     5,
     TYPE_ANIMAL,
     22,
     17,
     19,
     16,
     5,
     16,
     15,
     10,
     16,
     {{MG_LAND, 30}, {MG_BURROW, 10}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 1, 6, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 8, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_RAGE, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Horse Heavy",
     SIZE_LARGE,
     3,
     TYPE_ANIMAL,
     16,
     13,
     15,
     13,
     5,
     13,
     13,
     8,
     16,
     {{MG_LAND, 50}, {MG_NONE, 0}},
     {{{NW_HOOF, NAR_PRIMARY, 0, 1, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_HOOF, 2}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Horse Light",
     SIZE_LARGE,
     3,
     TYPE_ANIMAL,
     14,
     13,
     15,
     13,
     5,
     12,
     13,
     8,
     16,
     {{MG_LAND, 60}, {MG_NONE, 0}},
     {{{NW_HOOF, NAR_PRIMARY, 0, 1, 4, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_HOOF, 2}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Lion",
     SIZE_LARGE,
     5,
     TYPE_ANIMAL,
     21,
     17,
     15,
     15,
     5,
     15,
     13,
     10,
     16,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 1, 4, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 8, 0}, {NW_RAKE, NAR_SPECIAL, 0, 1, 4, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_POUNCE, 1}, {SA_IMPROVED_GRAB, 1}, {SA_RAKE, 2}}},
     ""},
    {"Manta Ray",
     SIZE_LARGE,
     4,
     TYPE_ANIMAL,
     15,
     11,
     10,
     12,
     5,
     12,
     11,
     7,
     16,
     {{MG_SWIM, 30}, {MG_NONE, 0}},
     {{{NW_RAM, NAR_PRIMARY, 0, 1, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_RAM, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Mule",
     SIZE_LARGE,
     3,
     TYPE_ANIMAL,
     16,
     13,
     17,
     13,
     5,
     13,
     14,
     8,
     16,
     {{MG_LAND, 30}, {MG_NONE, 0}},
     {{{NW_HOOF, NAR_PRIMARY, 0, 1, 4, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_HOOF, 2}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Octopus, Giant",
     SIZE_LARGE,
     8,
     TYPE_ANIMAL,
     20,
     15,
     13,
     18,
     10,
     15,
     12,
     9,
     16,
     {{MG_LAND, 20}, {MG_SWIM, 40}},
     {{{NW_TENTACLE, NAR_PRIMARY, 0, 1, 4, 0},
       {NW_BITE, NAR_SECONDARY, 0, 1, 8, 0},
       {NW_CONSTRICT, NAR_SPECIAL, ATTACK_PRESET, 2, 8, 6}},
      {{NW_TENTACLE, 8}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_IMPROVED_GRAB, 1}, {SA_CONSTRICT, 1}, {SA_NONE, 0}}},
     ""},
    {"Rhinoceros",
     SIZE_LARGE,
     8,
     TYPE_ANIMAL,
     26,
     10,
     21,
     16,
     5,
     18,
     16,
     7,
     16,
     {{MG_LAND, 30}, {MG_NONE, 0}},
     {{{NW_GORE, NAR_PRIMARY, 0, 2, 6, 0},
       {NW_POWERFULL_CHARGE, NAR_SPECIAL, 0, 4, 6, 24},
       {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_GORE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_POWERFUL_CHARGE, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Shark, Large",
     SIZE_LARGE,
     7,
     TYPE_ANIMAL,
     17,
     15,
     13,
     15,
     5,
     13,
     12,
     9,
     16,
     {{MG_SWIM, 60}, {MG_NONE, 0}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 8, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Viper, Large",
     SIZE_LARGE,
     3,
     TYPE_ANIMAL,
     10,
     17,
     11,
     15,
     5,
     10,
     11,
     10,
     16,
     {{MG_LAND, 20}, {MG_SWIM, 20}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 4, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_POISON, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Tiger",
     SIZE_LARGE,
     6,
     TYPE_ANIMAL,
     23,
     15,
     17,
     14,
     5,
     16,
     14,
     9,
     16,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 1, 8, 0}, {NW_BITE, NAR_SECONDARY, 0, 2, 6, 0}, {NW_RAKE, NAR_SPECIAL, 0, 1, 8, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_IMPROVED_GRAB, 1}, {SA_POUNCE, 1}, {SA_RAKE, 2}}},
     ""},
    {"Warhorse Heavy",
     SIZE_LARGE,
     4,
     TYPE_ANIMAL,
     18,
     13,
     17,
     14,
     5,
     14,
     14,
     8,
     16,
     {{MG_LAND, 50}, {MG_NONE, 0}},
     {{{NW_HOOF, NAR_PRIMARY, 0, 1, 6, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 4, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_HOOF, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Warhorse Light",
     SIZE_LARGE,
     3,
     TYPE_ANIMAL,
     16,
     13,
     17,
     14,
     5,
     13,
     14,
     8,
     16,
     {{MG_LAND, 60}, {MG_NONE, 0}},
     {{{NW_HOOF, NAR_PRIMARY, 0, 1, 4, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 3, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_HOOF, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Baboon",
     SIZE_MEDIUM,
     1,
     TYPE_ANIMAL,
     15,
     14,
     12,
     13,
     5,
     2,
     3,
     4,
     1,
     {{MG_LAND, 40}, {MG_CLIMB, 30}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Bear, Black",
     SIZE_MEDIUM,
     3,
     TYPE_ANIMAL,
     19,
     13,
     15,
     13,
     5,
     6,
     5,
     4,
     2,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 1, 4, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Boar",
     SIZE_MEDIUM,
     3,
     TYPE_ANIMAL,
     15,
     10,
     17,
     16,
     5,
     4,
     6,
     3,
     2,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_GORE, NAR_PRIMARY, 0, 1, 8, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_GORE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_FEROCITY, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Cheetah",
     SIZE_MEDIUM,
     3,
     TYPE_ANIMAL,
     16,
     19,
     15,
     15,
     5,
     5,
     5,
     7,
     2,
     {{MG_LAND, 50}, {MG_NONE, 0}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 6, 0}, {NW_CLAW, NAR_SECONDARY, 0, 1, 2, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_CLAW, 2}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_TRIP, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Crocodile",
     SIZE_MEDIUM,
     3,
     TYPE_ANIMAL,
     19,
     12,
     17,
     15,
     5,
     6,
     6,
     4,
     2,
     {{MG_LAND, 20}, {MG_SWIM, 30}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 8, 0}, {NW_TAIL_SLAP, NAR_PRIMARY, 0, 1, 12, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_TAIL_SLAP, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_IMPROVED_GRAB, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Dog, Riding",
     SIZE_MEDIUM,
     2,
     TYPE_ANIMAL,
     15,
     15,
     15,
     16,
     5,
     3,
     5,
     5,
     1,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Donkey",
     SIZE_MEDIUM,
     2,
     TYPE_ANIMAL,
     10,
     13,
     12,
     13,
     5,
     1,
     4,
     4,
     0,
     {{MG_LAND, 30}, {MG_NONE, 0}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 2, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Hyena",
     SIZE_MEDIUM,
     2,
     TYPE_ANIMAL,
     14,
     15,
     15,
     14,
     5,
     3,
     5,
     5,
     1,
     {{MG_LAND, 50}, {MG_NONE, 0}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_TRIP, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Leopard",
     SIZE_MEDIUM,
     3,
     TYPE_ANIMAL,
     16,
     19,
     15,
     15,
     5,
     5,
     5,
     7,
     2,
     {{MG_LAND, 40}, {MG_CLIMB, 20}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 6, 0}, {NW_CLAW, NAR_SECONDARY, 0, 1, 3, 0}, {NW_RAKE, NAR_SPECIAL, 0, 1, 3, 0}},
      {{NW_BITE, 1}, {NW_CLAW, 2}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_IMPROVED_GRAB, 1}, {SA_POUNCE, 1}, {SA_RAKE, 2}}},
     ""},
    {"Lizard, Monitor",
     SIZE_MEDIUM,
     3,
     TYPE_ANIMAL,
     17,
     15,
     17,
     15,
     5,
     5,
     8,
     5,
     2,
     {{MG_LAND, 30}, {MG_SWIM, 30}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 8, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Pony",
     SIZE_MEDIUM,
     2,
     TYPE_ANIMAL,
     13,
     13,
     12,
     13,
     5,
     2,
     4,
     4,
     0,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_HOOF, NAR_PRIMARY, 0, 1, 3, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_HOOF, 2}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Pony, War",
     SIZE_MEDIUM,
     2,
     TYPE_ANIMAL,
     15,
     13,
     14,
     13,
     5,
     3,
     5,
     4,
     0,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_HOOF, NAR_PRIMARY, 0, 1, 3, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_HOOF, 2}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Porpoise",
     SIZE_MEDIUM,
     2,
     TYPE_ANIMAL,
     11,
     17,
     13,
     15,
     5,
     1,
     4,
     6,
     1,
     {{MG_SWIM, 80}, {MG_NONE, 0}},
     {{{NW_SLAM, NAR_PRIMARY, 0, 2, 4, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_SLAM, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Shark, Medium",
     SIZE_MEDIUM,
     3,
     TYPE_ANIMAL,
     13,
     15,
     13,
     15,
     5,
     3,
     4,
     5,
     2,
     {{MG_SWIM, 60}, {MG_NONE, 0}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Constrictor Snake",
     SIZE_MEDIUM,
     3,
     TYPE_ANIMAL,
     17,
     17,
     13,
     15,
     5,
     5,
     4,
     6,
     2,
     {{MG_LAND, 20}, {MG_CLIMB, 20}, {MG_SWIM, 20}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 3, 0},
       {NW_CONSTRICT, NAR_SPECIAL, ATTACK_PRESET, 1, 3, 4},
       {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_CONSTRICT, 1}, {SA_IMPROVED_GRAB, 1}, {SA_NONE, 0}}},
     ""},
    {"Snake, Medium Viper",
     SIZE_MEDIUM,
     2,
     TYPE_ANIMAL,
     8,
     17,
     11,
     16,
     5,
     0,
     3,
     6,
     1,
     {{MG_LAND, 20}, {MG_CLIMB, 20}, {MG_SWIM, 20}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 4, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_POISON, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Squid",
     SIZE_MEDIUM,
     3,
     TYPE_ANIMAL,
     14,
     17,
     11,
     16,
     5,
     8,
     3,
     6,
     2,
     {{MG_SWIM, 60}, {MG_NONE, 0}},
     {{{NW_ARMS, NAR_PRIMARY, 0, 0, 0, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_ARMS, 1}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_IMPROVED_GRAB, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Wolf",
     SIZE_MEDIUM,
     2,
     TYPE_ANIMAL,
     13,
     15,
     15,
     14,
     5,
     2,
     5,
     5,
     1,
     {{MG_LAND, 50}, {MG_NONE, 0}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_TRIP, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Wolverine",
     SIZE_MEDIUM,
     3,
     TYPE_ANIMAL,
     14,
     15,
     19,
     14,
     5,
     4,
     7,
     5,
     2,
     {{MG_LAND, 30}, {MG_BURROW, 10}, {MG_CLIMB, 10}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 1, 4, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_RAGE, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Dire Badger",
     SIZE_MEDIUM,
     3,
     TYPE_ANIMAL,
     14,
     17,
     19,
     16,
     5,
     4,
     7,
     6,
     4,
     {{MG_LAND, 30}, {MG_BURROW, 10}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 1, 4, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_RAGE, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Dire Weasel",
     SIZE_MEDIUM,
     3,
     TYPE_ANIMAL,
     14,
     19,
     10,
     16,
     5,
     4,
     3,
     7,
     4,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 6, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_ATTACH, 1}, {SA_BLOOD_DRAIN, 1}, {SA_NONE, 0}}},
     ""},
    {"Badger",
     SIZE_SMALL,
     1,
     TYPE_ANIMAL,
     8,
     17,
     15,
     15,
     5,
     -5,
     4,
     5,
     1,
     {{MG_LAND, 30}, {MG_BURROW, 10}},
     {{{NW_CLAW, NAR_PRIMARY, 0, 1, 2, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 3, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_CLAW, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_RAGE, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Dog",
     SIZE_SMALL,
     1,
     TYPE_ANIMAL,
     13,
     17,
     15,
     15,
     5,
     -3,
     4,
     5,
     1,
     {{MG_LAND, 40}, {MG_NONE, 0}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 4, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Eagle",
     SIZE_SMALL,
     1,
     TYPE_ANIMAL,
     10,
     15,
     12,
     14,
     5,
     -4,
     3,
     4,
     2,
     {{MG_LAND, 10}, {MG_FLY_AVERAGE, 80}},
     {{{NW_TALON, NAR_PRIMARY, 0, 1, 4, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 4, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_TALON, 2}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_NONE, 0}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Octopus",
     SIZE_SMALL,
     2,
     TYPE_ANIMAL,
     12,
     17,
     11,
     16,
     5,
     2,
     3,
     6,
     1,
     {{MG_LAND, 20}, {MG_SWIM, 30}},
     {{{NW_ARMS, NAR_PRIMARY, 0, 0, 0, 0}, {NW_BITE, NAR_SECONDARY, 0, 1, 3, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_ARMS, 1}, {NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_IMPROVED_GRAB, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Snake, Small Viper",
     SIZE_SMALL,
     1,
     TYPE_ANIMAL,
     6,
     17,
     11,
     17,
     5,
     -6,
     2,
     5,
     1,
     {{MG_LAND, 20}, {MG_CLIMB, 20}, {MG_SWIM, 20}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 2, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_POISON, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
    {"Dire Rat",
     SIZE_SMALL,
     1,
     TYPE_ANIMAL,
     10,
     17,
     12,
     15,
     5,
     -4,
     3,
     5,
     3,
     {{MG_LAND, 40}, {MG_CLIMB, 20}},
     {{{NW_BITE, NAR_PRIMARY, 0, 1, 4, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}, {NW_NONE, NAR_NONE, 0, 0, 0, 0}},
      {{NW_BITE, 1}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}, {NW_NONE, 0}},
      {{SA_DISEASE, 1}, {SA_NONE, 0}, {SA_NONE, 0}}},
     ""},
};

const size_t total_creatures = sizeof(animals) / sizeof(animal_specs_t);
